spring.application.name=Issue Tracker

# Server Configuration
server.port=${SERVER_PORT:8090}

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true

# PostgreSQL Configuration
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Session
server.servlet.session.timeout=30m

# Security Configuration
